version: "3"

services:
  redis:
    container_name: user-session-redis
    image: redis
    command: redis-server
    ports:
      - "6379:6379"
    networks:
      - user-session-network
  express:
    container_name:  user-session-express
    image: user-session-express
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000"
    networks:
      - user-session-network
    volumes:
      - ./src:/user-session/src

  nginx:
    container_name: user-session-nginx
    image: user-session-nginx
    build:
      context: .
      dockerfile: Dockerfile.nginx
    networks:
      - user-session-network
    ports:
      - "8000:80"
networks:
  user-session-network:
    driver: bridge
